# Generated by Django 3.1.7 on 2021-03-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(verbose_name='Id do Cliente')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('sexo', models.CharField(max_length=255, verbose_name='Sexo')),
                ('creditlimit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Limite de Crédito')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderProduto_id', models.IntegerField(verbose_name='Id da ordem')),
                ('pedido_id', models.IntegerField(verbose_name='Id do Pedido')),
                ('sku', models.IntegerField(verbose_name='SKU')),
                ('qte', models.IntegerField(verbose_name='Quantidade')),
                ('precounit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Unitário')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(verbose_name='Id do Cliente')),
                ('datapgto', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('meiopgto', models.CharField(max_length=255, verbose_name='Meio de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.IntegerField(verbose_name='Id do Pedido')),
                ('cliente_id', models.IntegerField(verbose_name='Id do Cliente')),
                ('datapedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('datapgto', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('dataenvio', models.DateTimeField(verbose_name='Data do Envio')),
                ('status', models.IntegerField(verbose_name='Status')),
                ('fontemkt', models.CharField(max_length=255, verbose_name='Fonte de Marketing')),
                ('comentarios', models.CharField(max_length=255, verbose_name='Comentários')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(verbose_name='SKU')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('cor', models.CharField(max_length=255, verbose_name='Cor do Produto')),
                ('tamanho', models.CharField(max_length=255, verbose_name='Tamanho')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
        ),
    ]
