# Generated by Django 3.1.7 on 2021-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210310_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(max_length=1, verbose_name='Tamanho'),
        ),
    ]
