# Generated by Django 3.1.7 on 2021-03-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210310_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='orderproduto',
            name='OrderProduto_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_id',
        ),
    ]
