# Generated by Django 3.1.7 on 2021-03-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210311_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(choices=[(1, 'Bermuda'), (2, 'Calça'), (3, 'Camiseta'), (4, 'Blusa'), (5, 'Saia'), (6, 'Vestido')], verbose_name='Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='datapgto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pagamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='meiopgto',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito'), (2, 'Boleto'), (3, 'Pix'), (4, 'Transferência Bancária')], verbose_name='Meio de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dataenvio',
            field=models.DateField(verbose_name='Data do Envio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='datapedido',
            field=models.DateField(verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fontemkt',
            field=models.IntegerField(choices=[(1, 'Instagram'), (2, 'Facebook'), (3, 'Agência de Mkt')], verbose_name='Fonte de Marketing'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aguardando Pagamento'), (2, 'Em processamento'), (3, 'Enviado'), (4, 'Não Entregue'), (5, 'Entregue'), (6, 'Devolvido')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.CharField(max_length=10, verbose_name='Cor do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(max_length=10, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.IntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG'), (5, 'XG')], verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
